unit_tests:
  steps: &unit_tests
    - checkout
    - run:
        name: Install modules and dependencies.
        command: npm install
    - run:
        name: Run unit tests.
        command: npm test
    - run:
        name: Submit coverage data to codecov.
        command: node_modules/.bin/codecov
        when: always
version: 2
workflows:
  version: 2
  tests:
    jobs:
      - node4:
          filters:
            tags:
              only: /.*/
      - node6:
          filters:
            tags:
              only: /.*/
      - node8:
          filters:
            tags:
              only: /.*/
      - node9:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - node4
            - node6
            - node8
            - node9
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - node4
            - node6
            - node8
            - node9
          filters:
            tags:
              only: /.*/
      - system_tests:
          requires:
            - lint
            - docs
          filters:
            branches:
              only: master
            tags:
              only: '/^v[\d.]+$/'
      - publish_npm:
          requires:
            - system_tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[\d.]+$/'
jobs:
  node4:
    docker:
      - image: 'node:4'
        user: node
    steps:
      - checkout
      - run:
          name: Install modules and dependencies.
          command: npm install --unsafe-perm
      - run:
          name: Run unit tests.
          command: npm test
      - run:
          name: Submit coverage data to codecov.
          command: node_modules/.bin/codecov
          when: always
  node6:
    docker:
      - image: 'node:6'
        user: node
    steps: *unit_tests
  node8:
    docker:
      - image: 'node:8'
        user: node
    steps: *unit_tests
  node9:
    docker:
      - image: 'node:9'
        user: node
    steps: *unit_tests
  lint:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run:
          name: Install modules and dependencies.
          command: |
            mkdir -p /home/node/.npm-global
            npm install
            npm link
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run:
          name: Run linting.
          command: npm run lint
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
  docs:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run:
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Build documentation.
          command: npm run docs
  system_tests:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run:
          name: Decrypt credentials.
          command: |
            openssl aes-256-cbc -d -in .circleci/key.json.enc \
                -out .circleci/key.json \
                -k "${SYSTEM_TESTS_ENCRYPTION_KEY}"
      - run:
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Run system tests.
          command: npm run system-test
          environment:
            GCLOUD_PROJECT: long-door-651
            GOOGLE_APPLICATION_CREDENTIALS: .circleci/key.json
      - run:
          name: Remove unencrypted key.
          command: rm .circleci/key.json
          when: always
  publish_npm:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run:
          name: Set NPM authentication.
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Publish the module to npm.
          command: npm publish --access=public
