version: 2
workflows:
  version: 2
  tests:
    jobs: &workflow_jobs
      - node6:
          filters: &all_commits
            tags:
              only: /.*/
      - node8:
          filters: *all_commits
      - node10:
          filters: *all_commits
      - lint:
          requires:
            - node6
            - node8
            - node10
          filters: *all_commits
      - docs:
          requires:
            - node6
            - node8
            - node10
          filters: *all_commits
      - publish_npm:
          requires:
            - lint
            - docs
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[\d.]+$/'
  nightly:
    triggers:
      - schedule:
          cron: 0 7 * * *
          filters:
            branches:
              only: master
    jobs: *workflow_jobs
jobs:
  node6:
    docker:
      - image: 'node:6'
        user: node
    steps: &unit_tests_steps
      - checkout 
      - run: &npm_install_and_link
          name: Install and link the module
          command: |-
            mkdir -p /home/node/.npm-global
            npm install
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run: npm test
      - run: node_modules/.bin/codecov
  
  node8:
    docker:
      - image: 'node:8'
        user: node
    steps: *unit_tests_steps
  node10:
    docker:
      - image: 'node:10'
        user: node
    steps: *unit_tests_steps
  lint:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run: *npm_install_and_link
      - run:
          name: Link the module being tested to the samples.
          command: |
            cd samples/
            npm install
            npm link ../
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run:
          name: Run linting.
          command: npm run lint
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
  docs:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run: *npm_install_and_link
      - run:
          name: Build documentation.
          command: npm run docs
  publish_npm:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run: npm publish --access=public
